# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bracket Challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bracket Challenge

    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'

end
